name: CMake Windows Matrix Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        compiler: [msvc, mingw]
        build_type: [Release, Debug]
    
    env:
      BUILD_TYPE: ${{ matrix.build_type }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up MSVC
      if: matrix.compiler == 'msvc'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Add MinGW to PATH
      if: matrix.compiler == 'mingw'
      shell: bash
      run: echo "C:/Program Files/mingw-w64/mingw64/bin" >> $GITHUB_PATH

    - name: Configure CMake
      run: >
        cmake -B build
        -G "${{ matrix.compiler == 'msvc' && 'NMake Makefiles' || 'MinGW Makefiles' }}"
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: cmake --build build

    - name: Test
      working-directory: build
      run: ctest -C ${{ matrix.build_type }}
